# Generated by Django 3.2 on 2021-12-17 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0004_review_review_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review_user',
            new_name='review',
        ),
    ]
