# Generated by Django 3.2 on 2021-12-17 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0005_rename_review_user_review_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review',
        ),
    ]
